<!-- // AFFICHAGE HTML
// Affichage alernatif : remplacer { par : et } par endforeach; -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exo PHP - STUDENT AT SCHOOL</title>
</head>
<body>
    <header>        
        <h1><?php echo "^^ Exo PHP - STUDENT AT SCHOOL ^^"; ?></h1>
    </header>
    <main>
        
    
    </main>
            
</body>
</html>